version: '3.4'

services:
  dotnetappmetricsprototype:
    image: ${DOCKER_REGISTRY-}dotnetappmetricsprototype
    build:
      context: .
      dockerfile: DotnetAppMetricsPrototype/Dockerfile

  grafana:
    image: grafana/grafana
    container_name: grafana

  influxdb:
    image: influxdb
    container_name: influxdb

  prometheus:
    image: prom/prometheus
    container_name: prometheus


